name: ci-nodejs-workflow

defaults:
  run:
    working-directory: backend-app

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm test

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: false
      #     tags: murilohenzo/project-fulltstack:latest