name: ci-nodejs-workflow

defaults:
  run:
    working-directory: backend-app

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push postgres-db
        uses: docker/build-push-action@v2
        with:
          context: ./backend-app
          file: Dockerfile.db.dev
          push: false
          tags: murilohenzo/postgres_db

#       - name: Build and push nodejs-api
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: backend-app/Dockerfile.dev
#           push: false
#           tags: murilohenzo/nodejs-api
